### ISSUE TITLE
Treat `as` expressions as block-formattable if the subexpression is

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/dart_style#1542]
```dart
        final result = await buildDryRun(
          packageUri,
          createCapturingLogger(logMessages, level: Level.SEVERE),
          dartExecutable,
          linkingEnabled: false,
        );
```

->

```dart
        final result =
            await buildDryRun(
              packageUri,
              createCapturingLogger(logMessages, level: Level.SEVERE),
              dartExecutable,
              linkingEnabled: false,
            );
```

I'm not sure why the extra indentation is needed here. I expect this to be indented like it would be without an `await`

```dart
        final result = buildDryRun(
          packageUri,
          createCapturingLogger(logMessages, level: Level.SEVERE),
          dartExecutable,
          linkingEnabled: false,
        );
```

Is the await significant here? Or is it simply that the formatter deems the expression getting too big?

Source: https://github.com/dart-lang/native/blob/main/pkgs/native_assets_builder/test/build_runner/build_runner_cycle_test.dart

**Comment by dcharkes** [comment]
```dart
      final buildConfig = BuildConfig.build(
        outputDirectory: outputDirectory,
        packageName: await _packageName(),
        packageRoot: Directory.current.uri,
        buildMode: buildMode ?? BuildMode.release,
        targetArchitecture: targetArchitecture ?? Architecture.current,
        targetOS: targetOS ?? OS.current,
        linkModePreference: linkModePreference ?? LinkModePreference.dynamic,
        linkingEnabled: linkingEnabled ?? true,
        cCompiler: cCompiler,
        supportedAssetTypes: supportedAssetTypes,
        targetAndroidNdkApi: targetAndroidNdkApi,
        targetIOSSdk: targetIOSSdk,
        targetIOSVersion: targetIOSVersion,
        targetMacOSVersion: targetMacOSVersion,
      ) as BuildConfigImpl;
```

->

```dart
    final buildConfig =
        BuildConfig.build(
              outputDirectory: outputDirectory,
              packageName: await _packageName(),
              packageRoot: Directory.current.uri,
              buildMode: buildMode ?? BuildMode.release,
              targetArchitecture: targetArchitecture ?? Architecture.current,
              targetOS: targetOS ?? OS.current,
              linkModePreference:
                  linkModePreference ?? LinkModePreference.dynamic,
              linkingEnabled: linkingEnabled ?? true,
              cCompiler: cCompiler,
              supportedAssetTypes: supportedAssetTypes,
              targetAndroidNdkApi: targetAndroidNdkApi,
              targetIOSSdk: targetIOSSdk,
              targetIOSVersion: targetIOSVersion,
              targetMacOSVersion: targetMacOSVersion,
            )
            as BuildConfigImpl;
```

Is this similar as to the `await`? that an `as` prevents no indentation?

Source: https://github.com/dart-lang/native/blob/main/pkgs/native_assets_cli/lib/src/api/test.dart

**Comment by dcharkes** [comment]
Duplicate: https://github.com/dart-lang/dart_style/issues/1531

**Comment by dcharkes** [comment]
`await`s are fixed as of https://github.com/dart-lang/dart_style/pull/1538 ❤️ 

`as` expressions are not block-formatted.

**Comment by Reprevise** [comment]
One workaround is giving the variable a type instead of using a cast. It doesn't work in all cases though but I found it works well enough in the meantime while we wait for this to get fixed.

**Comment by munificent** [comment]
Fixed by https://github.com/dart-lang/dart_style/pull/1835.

**Comment by FMorschel** [comment]
@munificent, will this also work for if-null (`??`) expressions? 

Like:

```dart
Future<bool?> f() async {
  var _ =
      await f(
        //
      ) ??
      false;
  return await f(
        //
      ) ??
      false;
}
```

I've tried with `3.13.0-edge.6c86343d7234a80a2d178268d098dae4de6d8829` (from today) and the `pubspec.yaml` containing:

```yaml
environment:
  sdk: ^3.13.0-edge
```

Did I do something wrong, or is this not fixed?
